# shell /bin/zsh

# Fonts
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12

# Window
confirm_os_window_close 0
window_padding_width 15

# Background
background_opacity 0.70
background_blur 1

# Cursor Glitch
cursor_blink_interval 0.5
cursor_trail 3
cursor_trail_decay 0.1 0.4

# colors
include ~/.cache/wal/colors-kitty.conf

# Selection
selection_background #d1d1d1
selection_foreground #000000