# ----------------- hyprland conf -------------------------------

env = LANG,ru_RU.UTF-8

# NVIDIA
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# Cursor
env = XCURSOR_SIZE,24
env = XCURSOR_THEME,Bibata-Modern-Classic

# Imports conf

# Monitor
source = ~/.config/hypr/conf/monitor.conf

# Autostart
source = ~/.config/hypr/conf/autostart.conf

# Keyboard binds
source = ~/.config/hypr/conf/bind.conf

# Keyboard
source = ~/.config/hypr/conf/keyboard.conf

# Animation
source = ~/.config/hypr/conf/animation.conf

# Window rules
source = ~/.config/hypr/conf/windowrules.conf

# Misc
source = ~/.config/hypr/conf/misc.conf

# ---------------------------------------------------------------