# -----------------------------------------------------------

# Appearance of windows

source = ~/.config/hypr/script/colors-wal.conf

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = $color_active_1 $color_active_2 45deg
    col.inactive_border = rgba(595959aa)
}

animations {
    enabled = yes
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    bezier = easeOutQuint, 0.23, 1, 0.32, 1
    bezier = easeInOutCubic, 0.65, 0.05, 0.36, 1
    bezier = linear, 0, 0, 1, 1
    animation = windows, 1, 3, myBezier, popin 80%
    animation = windowsOut, 1, 3, easeOutQuint, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 4, easeOutQuint, slide
    animation = specialWorkspace, 1, 4, easeOutQuint, slidefadevert -20%
}

decoration {
    rounding = 15
    blur {
        enabled = true
        size = 7
        passes = 3
        ignore_opacity = true
        new_optimizations = true

        noise = 0.08
        contrast = 1.5
        xray = false
    }
}

# -----------------------------------------------------------