# -----------------------------------------------------------

exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP DISPLAY XAUTHORITY
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP DISPLAY XAUTHORITY

exec-once = killall -9 xdg-desktop-portal xdg-desktop-portal-hyprland 2>/dev/null
exec-once = /usr/lib/xdg-desktop-portal-hyprland &
exec-once = sleep 1 && /usr/lib/xdg-desktop-portal --replace &

# -----------------------------------------------------------

exec-once = xrandr --output DP-2 --primary

# -----------------------------------------------------------

exec-once = ~/.config/hypr/script/colors_in_wallpaper.sh &

# -----------------------------------------------------------

# Autostart
exec-once = waybar
exec-once = swaync
exec-once = awww-daemon
exec-once = gsr-ui
exec-once = vesktop --enable-features=UseOzonePlatform --ozone-platform=wayland
exec-once = steam
exec-once = hyprctl dispatch workspace 1

exec-once = openrgb --profile "MY"
exec-once = /media/nvme/My_Papka/TgWsProxy_linux_amd64

# -----------------------------------------------------------