# -----------------------------------------------------------

# base
$mainMod = SUPER
$terminal = kitty
$fileManager = nautilus
$menu = rofi -show drun

# binds
bind = $mainMod, T, exec, $terminal
bind = $mainMod, Q, killactive,
# bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, W, togglefloating,
bind = $mainMod, D, exec, $menu

# Mouse
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Switch workspace (SUPER + number)
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5

# Move window to another work. (SUPER + Shift + number)
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5

# Change focus between windows (SUPER + Arrows / HJKL)
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

# Move active window (SUPER + SHIFT + Arrows)
bind = $mainMod SHIFT, left, movewindow, l
bind = $mainMod SHIFT, right, movewindow, r
bind = $mainMod SHIFT, up, movewindow, u
bind = $mainMod SHIFT, down, movewindow, d

# Take a screenshot of the selected area and edit with swappy
bind = $mainMod SHIFT, S, exec, grim -g "$(slurp)" - | swappy -f -

# ALT + ENTER to full screen mode and return
bind = ALT, Return, fullscreen, 0

# Special workspace
bind = SUPER, grave, togglespecialworkspace
bind = SUPER SHIFT, grave, movetoworkspace, special

# Keyboard roller 
bindel = , XF86AudioRaiseVolume, exec, wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

# -----------------------------------------------------------
