# -----------------------------------------------------------

# First monitor --- right
monitor = DP-2, 2560x1440@180, 0x0, 1

# Second monitor --- left
monitor = HDMI-A-1, 1920x1080@60, -1920x0, 1

# -----------------------------------------------------------

# work. to first monitor
workspace = 1, monitor:DP-2, default:true
workspace = 2, monitor:DP-2
workspace = 3, monitor:DP-2
workspace = 4, monitor:DP-2
workspace = 5, monitor:DP-2

# work. for second monitor
workspace = 6, monitor:HDMI-A-1, default:true

# -----------------------------------------------------------