# Float Terminal
windowrule = float on, size 1070 700, match:class kitty

# Center all floating windows
windowrule = center on, match:float 1

# System
windowrule = float on, size 750 450, match:class blueman-manager
windowrule = float on, size 750 450, match:class org.pulseaudio.pavucontrol
windowrule = float on, size 1200 750, match:class org.gnome.Nautilus
windowrule = float on, size 600 400, match:class nm-connection-editor

# App
windowrule = float on, size 1500 1000, match:class codium
windowrule = float on, size 1500 900, match:class vesktop
windowrule = float on, size 1500 900, match:class org.telegram.desktop
windowrule = float on, size 1200 900, match:class openrgb
windowrule = float on, size 900 700, match:class waypaper
windowrule = float on, size 900 700, match:class mpv
windowrule = float on, size 1400 900, match:class zen
windowrule = float on, size 1400 900, match:class localsend
windowrule = float on, size 800 600, match:class org.xfce.mousepad
windowrule = float on, size 1280 720, match:class twintaillauncher
windowrule = float on, size 1200 780, match:class org.gnome.Loupe
windowrule = float on, size 395 616, match:class org.gnome.Calculator
windowrule = float on, size 1100 625, match:class com.linuxsoundboard.app
windowrule = float on, size 750 660, match:class warp-taskbar
windowrule = float on, size 1570 990, match:class Spotify
windowrule = float on, size 1570 990, match:class org.mozilla.Thunderbird

# hyprctl clients -j | jq -r '.[] | "\(.class): \(.size)"' узнать размер текущего окна